// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RouteForm from "./RouteForm.res.mjs";
import * as Create_map from "./Create_map.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var create_map = function (start, destination) {
    console.log("Start: " + start);
    console.log("Destination: " + destination);
  };
  var nodes = [
    {
      id: 244453411,
      lat: 39.2910,
      lon: -76.6120
    },
    {
      id: 244453412,
      lat: 39.2920,
      lon: -76.6130
    }
  ];
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Welcome to OCamaps"
                    }),
                JsxRuntime.jsx(RouteForm.make, {
                      onSubmit: create_map
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx(Create_map.make, {
                            nodes: nodes
                          })
                    })
              ]
            });
}

var make = App;

export {
  make ,
}
/* RouteForm Not a pure module */
