// Generated by ReScript, PLEASE EDIT WITH CARE


var buildingList = [
  {
    name: "amr 1"
  },
  {
    name: "amr 2"
  },
  {
    name: "amr 3"
  },
  {
    name: "o'connor recreation center"
  },
  {
    name: "UTL"
  },
  {
    name: "mudd hall"
  },
  {
    name: "macaulay hall"
  },
  {
    name: "dunning hall"
  },
  {
    name: "chemistry building"
  },
  {
    name: "mergenthaler hall"
  },
  {
    name: "remsen hall"
  },
  {
    name: "homewood museum"
  },
  {
    name: "milton s. eisenhower library"
  },
  {
    name: "krieger hall"
  },
  {
    name: "breezeway"
  },
  {
    name: "ames hall"
  },
  {
    name: "gilman hall"
  },
  {
    name: "glass pavilion"
  },
  {
    name: "levering hall"
  },
  {
    name: "greenhouse"
  },
  {
    name: "presidents garden"
  },
  {
    name: "johns hopkins club"
  },
  {
    name: "nichols house"
  },
  {
    name: "latrobe hall"
  },
  {
    name: "maryland hall"
  },
  {
    name: "brody learning commons"
  },
  {
    name: "merrick barn"
  },
  {
    name: "barton hall"
  },
  {
    name: "croft hall"
  },
  {
    name: "shaffer hall"
  },
  {
    name: "hackerman hall"
  },
  {
    name: "shriver hall"
  },
  {
    name: "malone hall"
  },
  {
    name: "homewood power plant"
  },
  {
    name: "mason hall"
  },
  {
    name: "clark hall"
  },
  {
    name: "hodson hall"
  },
  {
    name: "garland hall"
  },
  {
    name: "wyman park building"
  },
  {
    name: "bloomberg center"
  },
  {
    name: "olin hall"
  },
  {
    name: "cordish lacrosse center"
  },
  {
    name: "homewood field"
  },
  {
    name: "ROTC building"
  },
  {
    name: "imagine center"
  },
  {
    name: "scott-bates commons"
  },
  {
    name: "mccoy hall"
  },
  {
    name: "the beach"
  },
  {
    name: "the academy on charles"
  },
  {
    name: "nine east"
  }
];

export {
  buildingList ,
}
/* No side effect */
