// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function RouteForm(props) {
  var onSubmit = props.onSubmit;
  var handleSubmit = function (evt) {
    evt.preventDefault();
    onSubmit(evt);
  };
  return JsxRuntime.jsxs("form", {
              children: [
                JsxRuntime.jsxs("label", {
                      children: [
                        "Start:",
                        JsxRuntime.jsx("input", {
                              style: {
                                border: "1px solid black",
                                display: "block",
                                marginBottom: "10px",
                                padding: "8px",
                                width: "100%",
                                borderRadius: "3px"
                              },
                              type: "text"
                            })
                      ]
                    }),
                JsxRuntime.jsxs("label", {
                      children: [
                        "Destination:",
                        JsxRuntime.jsx("input", {
                              style: {
                                border: "1px solid black",
                                display: "block",
                                marginBottom: "10px",
                                padding: "8px",
                                width: "100%",
                                borderRadius: "3px"
                              },
                              type: "text"
                            })
                      ]
                    }),
                JsxRuntime.jsx("button", {
                      children: "Start",
                      style: {
                        backgroundColor: "#007bff",
                        border: "none",
                        color: "white",
                        cursor: "pointer",
                        marginTop: "10px",
                        padding: "8px 16px",
                        borderRadius: "5px"
                      },
                      type: "submit"
                    })
              ],
              style: {
                border: "1px solid black",
                display: "flex",
                margin: "10px",
                maxWidth: "300px",
                padding: "10px",
                borderRadius: "5px",
                alignItems: "flex-start",
                flexDirection: "column"
              },
              onSubmit: handleSubmit
            });
}

var make = RouteForm;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
