// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function RouteForm(props) {
  var onSubmit = props.onSubmit;
  var match = React.useState(function () {
        return "";
      });
  var setStart = match[1];
  var start = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setDestination = match$1[1];
  var destination = match$1[0];
  var handleSubmit = function (evt) {
    evt.preventDefault();
    if (start === "" || destination === "") {
      console.log("Error: Both Start and Destination must be filled!");
      return ;
    } else {
      return onSubmit(start, destination);
    }
  };
  return JsxRuntime.jsxs("form", {
              children: [
                JsxRuntime.jsxs("label", {
                      children: [
                        "Start:",
                        JsxRuntime.jsx("input", {
                              style: {
                                border: "1px solid black",
                                display: "block",
                                marginBottom: "10px",
                                padding: "8px",
                                width: "100%",
                                borderRadius: "3px"
                              },
                              type: "text",
                              value: start,
                              onChange: (function (evt) {
                                  setStart(evt.target.value);
                                })
                            })
                      ]
                    }),
                JsxRuntime.jsxs("label", {
                      children: [
                        "Destination:",
                        JsxRuntime.jsx("input", {
                              style: {
                                border: "1px solid black",
                                display: "block",
                                marginBottom: "10px",
                                padding: "8px",
                                width: "100%",
                                borderRadius: "3px"
                              },
                              type: "text",
                              value: destination,
                              onChange: (function ($$event) {
                                  setDestination($$event.target.value);
                                })
                            })
                      ]
                    }),
                JsxRuntime.jsx("button", {
                      children: "Start",
                      style: {
                        backgroundColor: "#007bff",
                        border: "none",
                        color: "white",
                        cursor: "pointer",
                        marginTop: "10px",
                        padding: "8px 16px",
                        borderRadius: "5px"
                      },
                      type: "submit"
                    })
              ],
              style: {
                border: "1px solid black",
                display: "flex",
                margin: "10px",
                maxWidth: "300px",
                padding: "10px",
                borderRadius: "5px",
                alignItems: "flex-start",
                flexDirection: "column"
              },
              onSubmit: handleSubmit
            });
}

var make = RouteForm;

export {
  make ,
}
/* react Not a pure module */
